### ISSUE TITLE
Error of sending of remocon status

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#100]
RemoconStatus message has no `running_app` property. So, this error is happened. 

```
Traceback (most recent call last):
  File "/home/dwlee/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/../../scripts/rocon_remocon_sub", line 55, in <module>
    myapp = rocon_remocon.RemoconSub(None, "Rocon Remocon Sub", app, index, name, ip, host_name)
  File "/home/dwlee/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/remocon.py", line 87, in __init__
    self._init()
  File "/home/dwlee/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/remocon.py", line 90, in _init
    self._init_role_list()
  File "/home/dwlee/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/remocon.py", line 106, in _init_role_list
    if not self.remocon_info._connect(self.rocon_master_name, self.rocon_master_uri, self.host_name):
  File "/home/dwlee/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/remocon_info.py", line 105, in _connect
    self._pub_remocon_status(0, False)
  File "/home/dwlee/rocon/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/remocon_info.py", line 144, in _pub_remocon_status
    remocon_status.running_app = running_app
AttributeError: 'RemoconStatus' object has no attribute 'running_app'

```

**Comment by stonier** [comment]
The indigo branches have this fixed.

**Comment by stonier** [comment]
Ack...accidentally synced instead of pull requesting. These changes easily seen here.
- [remocon changes](https://github.com/robotics-in-concert/rocon_qt_gui/compare/82011d0917594147b6561f4c828ae216910b773e...563fe93f027516c56e4df8b107189650c0e1b2fe?expand=1)
- [rocon_msgs changes](https://github.com/robotics-in-concert/rocon_msgs/compare/f1472c609c586e652d1f8d1b5edf87e145cf3d86...bbf7802ee8f7a3873892c06b0f3d1403f32fd05a)
