### ISSUE TITLE
[remocon] Failure when early connecting to the interactions manager

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_qt_gui#111]
Sometimes I'm starting the remocon, when the app manager is still loading, in which case the interactions manager has not yet loaded the available interactions. In this case the remocon connects, but shows an empty list of roles.

Refreshing the list does not help:

```
$ rocon_remocon
[debug] InteractiveClient : initialised
[debug] InteractiveClient : Connection Details
[debug] InteractiveClient :   Node Name: rqt_remocon_8e4af37eae2c46ed817d432f792c4205
[debug] InteractiveClient :   ROS_MASTER_URI: http://localhost:11311
[debug] InteractiveClient :   ROS_HOSTNAME: localhost
[error] InteractiveClient : failed to find all of the interactions' publications and services [timed out]
Traceback (most recent call last):
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/interactions_chooser.py", line 134, in _refresh_role_list
    role_list = self.interactive_client.get_role_list()
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/interactive_client.py", line 136, in get_role_list
    response = self.get_roles_service_proxy(self.platform_info.uri)
AttributeError: InteractiveClient instance has no attribute 'get_roles_service_proxy'
```

Also, going back and connecting to the robot/interaction manager again does not help either:

```
[warning] InteractiveClient : tried to shutdown already disconnected remocon
[debug] InteractiveClient : initialised
[debug] InteractiveClient : Connection Details
[debug] InteractiveClient :   Node Name: rqt_remocon_dbc9b22874cc46d6bd4da1dfcbec2094
[debug] InteractiveClient :   ROS_MASTER_URI: http://localhost:11311
[debug] InteractiveClient :   ROS_HOSTNAME: localhost
[error] InteractiveClient : failed to find all of the interactions' publications and services [Unable to communicate with service [/rqt_remocon_8e4af37eae2c46ed817d432f792c4205/set_logger_level], address [rosrpc://localhost:35321]]
Traceback (most recent call last):
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/interactions_chooser.py", line 134, in _refresh_role_list
    role_list = self.interactive_client.get_role_list()
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_remocon/src/rocon_remocon/interactive_client.py", line 136, in get_role_list
    response = self.get_roles_service_proxy(self.platform_info.uri)
AttributeError: InteractiveClient instance has no attribute 'get_roles_service_proxy'
```

The only solution so far is to shut down both the remocon and my launcher containing both the interactions manager and app manager (haven't tested the case of only restarting the interactions manager).

**Comment by stonier** [comment]
Implemented a check to see if the detection had succeeded. If not, it will provide a warning message box and drop back to the master chooser widget.
