### ISSUE TITLE
[concert_admin_app] unexpected type 'float'  value error

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_qt_gui#157]
```
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_qt_gui/concert_admin_app/src/concert_admin_app/admin_app.py", line 145, in _select_service_tree_item
    self._set_parameter_layout()
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_qt_gui/concert_admin_app/src/concert_admin_app/admin_app.py", line 173, in _set_parameter_layout
    value = QTextEdit(params[param])
TypeError: arguments did not match any overloaded call:
  QTextEdit(QWidget parent=None): argument 1 has unexpected type 'float'
  QTextEdit(QString, QWidget parent=None): argument 1 has unexpected type 'float'
```

**Comment by jihoonl** [comment]
https://github.com/robotics-in-concert/rocon_qt_gui/commit/8b1d7296305b61e6afe17a2c09ace740805e00f1
