### ISSUE TITLE
[rocon_remocon]  cannot find ui file in deb version

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_qt_gui#172]
```
yujin@alien:~$ rocon_remocon 
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rocon_remocon", line 55, in <module>
    myapp = rocon_remocon.QMasterChooser(None, "Rocon Remocon", app)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rocon_remocon/master_chooser.py", line 45, in __init__
    self._init_widget()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rocon_remocon/master_chooser.py", line 85, in _init_widget
    loadUi(path, self._widget_main)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 257, in loadUi
    return _loadUi(uifile, baseinstance, custom_widgets)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 156, in _loadUi
    return uic.loadUi(uifile, baseinstance=baseinstance)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py", line 71, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 943, in parse
    document = parse(filename)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/opt/ros/indigo/lib/python2.7/dist-packages/rocon_remocon/../../ui/remocon.ui'
[info] RemoconMain: Destroy
```

**Comment by jihoonl** [comment]
It
