### ISSUE TITLE
when termination of the check up concert sub-process, error occured

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#21]
This occurs when checking for concerts - assuming it happens in all cases here. 1) When starting 2) When back from the role list, 3) When refreshing

```
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/registration.py", line 275, in start
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/registration.py", line 307, in run
  File "/usr/lib/python2.7/threading.py", line 141, in release
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread /concert/info (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 504, in run
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_pubsub.py", line 178, in robust_connect_subscriber
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 763, in receive_loop
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by dwlee** [comment]
I fixed.
656c422
