### ISSUE TITLE
Change the msg type

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_qt_gui#31]
The error occurs because the change the message type

```
[ERROR] [WallTime: 1386925015.402578] bad callback: <bound method ConductorGraphInfo.update_client_list of <rocon_conductor_graph.conductor_graph_info.ConductorGraphInfo object at 0x2c74990>>
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 681, in _invoke_callback
    cb(msg)
  File "/home/yujin/demos/rocon_demo_201311/src/rocon_qt_gui/rocon_conductor_graph/src/rocon_conductor_graph/conductor_graph_info.py", line 76, in update_client_list
    self._client_info_list[client_name]["os"]=k.os
AttributeError: 'ConcertClient' object has no attribute 'os'
```

**Comment by dwlee** [comment]
fixed
6e744bd..6ee0570
