### ISSUE TITLE
Error when check the new concert validation

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_qt_gui#70]
In check up the concert validation with concert list information, 
If remocon tries to connect the wrong concert ip(ex. not running ros master pc), the `rospy.init_node()` function is blocking. So, when doing `crtl+v` or terminate checkup process, the exception below error raised.

```
Traceback (most recent call last):
  File "/home/dwlee/rocon/src/rocon_qt_gui/rocon_remocon/scripts/rocon_remocon_check_up", line 30, in <module>
    rospy.init_node("rocon_remocon_checker", anonymous=True)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/client.py", line 330, in init_node
    raise rospy.exceptions.ROSInitException("Failed to initialize time. Please check logs for additional details")
rospy.exceptions.ROSInitException: Failed to initialize time. Please check logs for additional details
```

**Comment by dwlee** [comment]
I fixed it.
f31eaa1..78b19fa
