### ISSUE TITLE
[app manager ui] UI does not find app manager

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_qt_gui#92]
Currently the UI only works with the standalone launcher. When using the app manager in other scenarios, the UI cannot find the app manager.

I guess this is due to different names of the app manager. For example, app manager name in the standalone launcher is `app manager`. But with Kobuki it is `kobuki`. Hence the topic/service names change as well, e.g. `/app_manager/list_apps` and `/kobuki/list_apps`. If this is the problem, then you need to search for _relative_ names of the topics/services instead of the _absolute_. For example, search for `list_apps` instead of `/app_manager/list_apps`.

**Comment by bit-pirate** [comment]
@dwlee It looks like this issue is back. The qt app manager fails to start, because it cant find `/list_rapps`. However, that service is available at `/turtlebot/list_rapps`. Here is the log:

```
$ rosservice list
/app_manager/get_loggers
/app_manager/set_logger_level
/capability_server/establish_bond
/capability_server/free_capability
/capability_server/get_capability_spec
/capability_server/get_capability_specs
/capability_server/get_interfaces
/capability_server/get_loggers
/capability_server/get_nodelet_manager_name
/capability_server/get_providers
/capability_server/get_remappings
/capability_server/get_running_capabilities
/capability_server/get_semantic_interfaces
/capability_server/reload_capabilities
/capability_server/set_logger_level
/capability_server/start_capability
/capability_server/stop_capability
/capability_server/use_capability
/capability_server_nodelet_manager/get_loggers
/capability_server_nodelet_manager/list
/capability_server_nodelet_manager/load_nodelet
/capability_server_nodelet_manager/set_logger_level
/capability_server_nodelet_manager/unload_nodelet
/interactions/get_interaction
/interactions/get_interactions
/interactions/get_loggers
/interactions/get_roles
/interactions/request_interaction
/interactions/set_interactions
/interactions/set_logger_level
/master/get_loggers
/master/set_logger_level
/rosout/get_loggers
/rosout/set_logger_level
/turtlebot/invite
/turtlebot/list_rapps
/turtlebot/platform_info
/turtlebot/start_rapp
/turtlebot/stop_rapp
/zeroconf/add_listener
/zeroconf/add_service
/zeroconf/list_discovered_services
/zeroconf/list_published_services
/zeroconf/remove_listener
/zeroconf/remove_service
/zeroconf/zeroconf/get_loggers
/zeroconf/zeroconf/set_logger_level
$ rocon_qt_app_manager
Traceback (most recent call last):
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager.py", line 74, in _change_namespace
    self.qt_app_manager_info._get_apps(self._widget.namespace_cbox.currentText())
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager_info.py", line 93, in _get_apps
    self._update_apps(service_handle())
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
rospy.service.ServiceException: service [/list_rapps] unavailable
PluginManager._load_plugin() could not load plugin "rocon_qt_app_manager/App Manger":
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 98, in load
    self._load()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 94, in load
    return class_ref(plugin_context)
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager.py", line 71, in __init__
    self._get_name_spaces()
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager.py", line 82, in _get_name_spaces
    self.qt_app_manager_info._get_apps(self._widget.namespace_cbox.currentText())
  File "/opt/rocon_workspace/src/rocon_qt_gui/rocon_qt_app_manager/src/rocon_qt_app_manager/qt_app_manager_info.py", line 93, in _get_apps
    self._update_apps(service_handle())
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
ServiceException: service [/list_rapps] unavailable

```

**Comment by kentsommer** [comment]
Once the following have been merged this issue is fixed. The change I made to remove name spacing on standalone launches (pull 245 below) could potentially hide this issue so I tested with name spacing re-enabled and everything runs as intended still. 
- [x] https://github.com/robotics-in-concert/rocon_app_platform/pull/245
- [ ] https://github.com/robotics-in-concert/rocon_app_platform/pull/243
- [x] https://github.com/robotics-in-concert/rocon_msgs/pull/94
- [x] https://github.com/robotics-in-concert/rocon_tools/pull/55
- [ ] https://github.com/robotics-in-concert/rocon_qt_gui/pull/139
